artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1zbilaliA_PAH7xMBGsrgYEuwb-PzvS6T/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.csv


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

# training:
#   root_dir: artifacts/training
#   trained_model_path: artifacts/training/model.h5

# project_name: Predicting_Bitcoin_Prices_Using_ANN

training:
  root_dir: artifacts/training
  updated_base_model_path: artifacts/prepare_base_model/base_model.h5
  trained_model_path: artifacts/model/trained_model.h5
  data_file: artifacts/data_preparation/train_val_data.pkl
  model_save_dir: artifacts/model
  
  epochs_final: 50
  batch_size: 32

# ann_training:
#   root_dir: artifacts/training
#   updated_base_model_path: artifacts/prepare_base_model/updated_model.h5
#   trained_model_path: artifacts/model/trained_model.h5
#   data_file: artifacts/data_preparation/train_val_data.pkl
#   model_save_dir: artifacts/model
#   epochs_final: 50
#   batch_size: 32
